# Generated by Django 3.2 on 2022-09-18 15:51

from django.db import migrations, models
import utils.generator


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.generator.generator, max_length=8, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_used',
            field=models.BooleanField(default=False, verbose_name='Code Used'),
        ),
    ]
