# Generated by Django 3.2 on 2022-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20220918_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Company')),
                ('logo', models.ImageField(upload_to='company', verbose_name='Logo')),
                ('about', models.TextField(blank=True, max_length=300, null=True, verbose_name='about')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Face Book')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('ins_link', models.URLField(blank=True, null=True, verbose_name='Instegram')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
            ],
        ),
    ]
