# Generated by Django 3.2 on 2022-09-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='', upload_to='Brand/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
