# Generated by Django 4.1.1 on 2022-09-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
